name: React App using github page

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install Dependencies
      - name: install Dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build

        # Deploy to the github pages
      - name: Deploy to the github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist
